---
- hosts: "{{ hosts }}"
  become: true
  tasks:
    - name: validar conexion apache
      uri:
        url: "http://{{ hosts }}"
      ignore_errors: true
    - name: mensaje
      debug:
        msg: continuo