# primero
---
- hosts: "{{ hosts }}"
  become: true
  tasks:
    - name: insatalamos apache
      package:
        name: httpd
        state: latest
      tags: install
    - name: levantar servicio httpd y persistente
      service: 
        name: httpd
        state: started
        enabled: yes 
      tags: config
    - name: creamos index.html
      file:
        path: /var/www/html/index.html
        state: touch
      tags: config
    - name: añadioms contenido a index
      copy:
        content: "Hello Word"
        dest: /var/www/html/index.html
      tags: config
    - name: desinstalar apache
      package:
        name: httpd
        state: absent
      tags: never,uninstall